garanty.acv.ru/models/ImportShip.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "z_import_ship".
 *
 * @property integer $id
 * @property integer $date
 * @property string $serial
 * @property string $sku
 * @property string $contragent
 */
class ImportShip extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'z_import_ship';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['date'], 'integer'],
            [['serial', 'sku', 'contragent'], 'string', 'max' => 255],
            [['serial'], 'unique'],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'date' => 'Date',
            'serial' => 'Serial',
            'sku' => 'Sku',
            'contragent' => 'Contragent',
        ];
    }

    public function getImportWarranty()
    {
        return $this->hasOne(ImportWarranty::className(), ['sku' => 'sku']);
    }

    public function checkTo($serial)
    {
        return Yii::$app->db->createCommand("SELECT * FROM z_registrylist WHERE serial = :serial", [':serial' => $serial])->queryOne();
    }
}

garanty.acv.ru/controllers/SiteController.php
<?php

namespace app\controllers;

use app\models\ImportShip;
use app\models\ImportWarranty;
use app\models\Registrylist;
use app\models\Search;
use app\models\Service;
use app\models\Settings;
use DateTime;
use Yii;
use yii\bootstrap\ActiveForm;
use yii\filters\AccessControl;
use yii\helpers\ArrayHelper;
use yii\web\Controller;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use app\models\ContactForm;
use yii\web\Response;
use yii\web\UploadedFile;

class SiteController extends Controller
{
    CONST ACV = 1;
    CONST RADIJATOR = 2;

    public function getTypes()
    {
        return [
            self::ACV => 'ACV',
            self::RADIJATOR => 'Radijator'
        ];
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        $model = new Search();

        $items = ImportWarranty::find()->where(['brand' => 'ACV'])->orderBy('name')->all();
        $items = ArrayHelper::map($items,'sku','name');

        return $this->render('index', [
            'brand' => $this->getTypes(),
            'model' => $model,
            'items' => $items
        ]);
    }

    public function actionMakeService()
    {
        $this->layout = 'inner';
        $model = new Service();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {

            // send mail
            $model->sendEmail(
                'mos@acv-rus.com',
                $model->email,
                "ACV; Ваша заявка в работе",
                "<p>пасибо $model->name, что обратились к нам в компанию. Ваша заявка № "
                . $model->order_name . " принята и назначена в ближайший авторизированный
                 сервисный центр ACV. В ближайшее время с Вами свяжутся.</p>
                 <p>С уважением, коллектив ACV Rus <br>
                  Москва, 8-я ул. Текстильщиков 11, офис 220 <br>
                  Тел. +7 499 272 19 65 <br>
                   www.acv.ru</p>"
                );

            Yii::$app->session->setFlash(
                'success',
                "Спасибо $model->name, Ваша заявка № $model->order_name принята и назначена в ближайший авторизированный сервисный центр ACV. В ближайшее время с Вами свяжется представитель сервисного центра.");
            return $this->redirect(Yii::$app->request->url, 302);
        } else {
            $items = ImportWarranty::find()->orderBy('name')->all();
            $items = ArrayHelper::map($items,'sku','name');

            $regions = Yii::$app->db->createCommand("SELECT * FROM region ORDER BY name")->queryAll();
            $regions = ArrayHelper::map($regions,'id','name');

            $cities = Yii::$app->db->createCommand("SELECT * FROM city WHERE region_id = 0  ORDER BY name")->queryAll();
            $cities = ArrayHelper::map($cities,'id','name');

            return $this->render('make-service', [
                'model' => $model,
                'items' => $items,
                'regions' => $regions,
                'cities' => $cities,
            ]);
        }
    }

    public function actionCallService()
    {
        $this->layout = 'inner';
        $model = new Service();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {

            // send mail
            $model->sendEmail(
                'mos@acv-rus.com',
                $model->email,
                "ACV; Ваша заявка в работе",
                "<p>пасибо $model->name, что обратились к нам в компанию. Ваша заявка № "
                . $model->order_name . " принята и назначена в ближайший авторизированный
                 сервисный центр ACV. В ближайшее время с Вами свяжутся.</p>
                 <p>С уважением, коллектив ACV Rus <br>
                  Москва, 8-я ул. Текстильщиков 11, офис 220 <br>
                  Тел. +7 499 272 19 65 <br>
                   www.acv.ru</p>"
                );

            Yii::$app->session->setFlash(
                'success',
                "Спасибо $model->name, Ваша заявка № $model->order_name принята и назначена в ближайший авторизированный сервисный центр ACV. В ближайшее время с Вами свяжется представитель сервисного центра.");
            return $this->redirect(Yii::$app->request->url, 302);
        } else {
            $items = ImportWarranty::find()->orderBy('name')->all();
            $items = ArrayHelper::map($items,'sku','name');

            $regions = Yii::$app->db->createCommand("SELECT * FROM region ORDER BY name")->queryAll();
            $regions = ArrayHelper::map($regions,'id','name');

            $cities = Yii::$app->db->createCommand("SELECT * FROM city WHERE region_id = 0  ORDER BY name")->queryAll();
            $cities = ArrayHelper::map($cities,'id','name');

            return $this->render('call-service', [
                'model' => $model,
                'items' => $items,
                'regions' => $regions,
                'cities' => $cities,
            ]);
        }
    }

    public function actionRegistryList()
    {
        $this->layout = 'inner';
        $model = new Registrylist();

        if ($model->load(Yii::$app->request->post())) {
            $model->file1 = UploadedFile::getInstance($model, 'file1');
            $model->file2 = UploadedFile::getInstance($model, 'file2');
            $model->file3 = UploadedFile::getInstance($model, 'file3');

            if ($model->validate() && $model->save(false)) {
                if ($model->id) {
                    $path = realpath(dirname(__FILE__)).'/../web/uploads/registrylist/' . $model->id . '/';
                    if ( !is_dir($path) ) {
                        mkdir( $path );
                    }

                    $model->file1->saveAs( $path . $model->file1);
                    $model->file2->saveAs( $path . $model->file2);
                    if ($model->file3) {
                        $model->file3->saveAs( $path . $model->file3);
                    }

                    $import_ship = ImportShip::find()->where(['serial' => $model->serial])->one();
                    $import_warranty = ImportWarranty::find()->where(['sku' => $model->model])->one();

                    if ($import_ship && $import_warranty) {
    //                    if ($import_warranty->type == 2) {

                        $full = $import_warranty->base + $import_warranty->more;
                        $endWarrantyTimestamp = setWarrantyTimestamp($full, $import_ship->date);

                        $message = "Поздравляем, срок гарантии для Вашего котла продлен на $full месяцев. Обращаем Ваше внимание, что для сохранения гарантии необходимо осуществлять правильную эксплуатацию и своевременное обслуживание оборудования. Подробнее с гарантийными условиями Вы можете ознакомиться по <a href='http://warranty.acv.ru/uploads/Warranty%20condition%2003042017.pdf' target='_blank'>ссылке</a>";

                        // send mail
                        $service = new Service();
                        $service->sendEmail(
                            'mos@acv-rus.com',
                            $model->email,
                            "ACV; регистрация пуска котла:",
                            "<p>$message</p>"
                        );

                        Yii::$app->db->createCommand()->update('z_import_ship', ['start_pusk' => time(), 'end_warranty' => $endWarrantyTimestamp], ['id' => $import_ship->id])->execute();
                        Yii::$app->session->setFlash(
                            'success',
                            $message);
    //                    }
                    } else {
                        Yii::$app->session->setFlash(
                            'warning',
                            "Cерийного номера не существует среди проданного оборудования! 
                    Регистрация выполнена частично, свяжитесь с тех поддержкой ACV!
                    ");
                    }
                }
            }
           return $this->redirect(Yii::$app->request->url, 302);
        } else {
            $items = ImportWarranty::find()->orderBy('name')->all();
            $items = ArrayHelper::map($items,'sku','name');

            $regions = Yii::$app->db->createCommand("SELECT * FROM region ORDER BY name")->queryAll();
            $regions = ArrayHelper::map($regions,'id','name');

            $cities = Yii::$app->db->createCommand("SELECT * FROM city WHERE region_id = 0  ORDER BY name")->queryAll();
            $cities = ArrayHelper::map($cities,'id','name');


            return $this->render('registry-list', [
                'model' => $model,
                'items' => $items,
                'regions' => $regions,
                'cities' => $cities,
            ]);
        }
    }

    public function actionCheckSerial()
    {
        Yii::$app->response->format = Response::FORMAT_JSON;
        $serial = Yii::$app->request->post('Service')['serial'];
        $sku = Yii::$app->request->post('Service')['model'];

garanty.acv.ru/views/site/call-service.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Url;
use yii\widgets\ActiveForm;
use yii\helpers\Html;
use yii\widgets\Breadcrumbs;

$this->title = 'Вызов специалиста при поломке оборудования';

$this->params['breadcrumbs'][] = $this->title;
echo Breadcrumbs::widget([
    'homeLink' => ['label' => 'Проверка гарантии', 'url' => '/'],
    'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
]);
?>

<div class="service-form">
    <h1>Вызов специалиста при поломке оборудования:</h1>
    <section class = 'form-search form-full'>
            <?php
            $form = ActiveForm::begin([
                'id' => 'search-form',
                'enableAjaxValidation' => true,
                'action' => 'call-service',
                'validationUrl' => 'check-serial',
                'options' => [
                    'class' => 'form-horizontal',
                    'enctype' => 'multipart/form-data'
                ],
            ]);
            ?>
        <div class="row">
            <div>
                <strong>Введите персональные данные:</strong>
            </div>
            <div class="col-md-4 col-sm-4 col-xs-12">
                <div class="control-group">
                    <?= $form->field($model, 'name')->textInput(['style' => 'margin: 0 auto;', 'placeholder' => $model->getAttributeLabel('name')])->label(''); ?>
                </div>
            </div>
            <div class="col-md-4 col-sm-4 col-xs-12">
                <div class="control-group">
                    <?= $form->field($model, 'surname')->textInput(['style' => 'margin: 0 auto;', 'placeholder' => $model->getAttributeLabel('surname')])->label(''); ?>
                </div>
            </div>
            <div class="col-md-4 col-sm-4 col-xs-12">
                <div class="control-group">
                    <?= $form->field($model, 'last_name')->textInput(['style' => 'margin: 0 auto;', 'placeholder' => $model->getAttributeLabel('last_name')])->label(''); ?>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-md-6 col-sm-6 col-xs-12">
                <div class="control-group">
                    <?= $form->field($model, 'phone')->widget(\yii\widgets\MaskedInput::className(), [
                        'mask' => '+7(999)999-99-99',
                        'options'=>[
                            'placeholder' => $model->getAttributeLabel('phone'),
                            'class'=>'form-control tel_input',
                            'style' => 'margin: 0 auto;'
                        ],
                    ])->label('') ?>
                </div>
            </div>
            <div class="col-md-6 col-sm-6 col-xs-12">
                <div class="control-group">
                    <?= $form->field($model, 'email')->textInput(['style' => 'margin: 0 auto;', 'placeholder' => $model->getAttributeLabel('email')])->label(''); ?>
                </div>
            </div>
        </div>

            <div class="row">
                <div><strong>Введите данные об оборудовании:</strong></div>
                <div class="col-md-6 col-sm-6 col-xs-12">
                    <div class="control-group">
                        <?= $form->field($model, 'model')->dropDownList($items, ['class' => 'selectpicker', 'data-live-search' => 'true'])->label(''); ?>
                    </div>
                </div>
                <div class="col-md-6 col-sm-6 col-xs-12">
                    <div class="control-group">
                        <?= $form->field($model, 'serial', ['enableAjaxValidation' => true])->textInput(['style' => 'margin: 0 auto;', 'placeholder' => 'Введите серийный номер'])->label(''); ?>
                    </div>
                </div>
            </div>

            <div class="row warranty_data" style="display:none;">
                <div><strong>Данные о гарантии:</strong></div>
                <div><strong>До окончания гарантийного срока осталось:</strong></div>
                <section class="info-box">
                    <div class = 'term'>
                        <p class = 'number'></p><span class = 'string'>&nbsp;&nbsp;&nbsp;&nbsp;месяцев</span>
                    </div>
                    <div class = 'term'>
                        <p class = 'number2'></p><span class = 'string'>&nbsp;&nbsp;&nbsp;&nbsp;дней</span>
                    </div>
                </section>
                <br>
                <br>
            </div>

            <div class="row warranty_hidden" style="<?= ($model->serial) ? ' '  : ' display: none' ?>">
                <div><strong>Данные о гарантии:</strong></div>
                <div class="col-xs-12">
                    <div class="control-group">
                        <?= $form->field($model, 'warranty_item')->textInput(['style' => 'margin: 0 auto; width: 80%', 'placeholder' => 'Введите номер гарантийного талона'])->label(''); ?>
                    </div>
                </div>
            </div>

            <div class="row">
                <div><strong>Место установки оборудования:</strong></div>
                <div class="col-md-4 col-sm-4 col-xs-12">
                    <div class="control-group">
                        <?= $form->field($model, 'region_id')->dropDownList($regions, ['class' => 'selectpicker', 'data-live-search' => 'true', 'options' =>[ '0' => ['selected' => true]]])->label(''); ?>
                    </div>
                </div>
                <div class="col-md-4 col-sm-4 col-xs-12">
                    <div class="control-group">
                        <?= $form->field($model, 'city_id')->dropDownList($cities, [
                            'class' => 'selectpicker',
                            'data-live-search' => 'true',
                            'options' =>[ '1' => ['selected' => true]]
                        ])->label(''); ?>
                    </div>
                </div>
                <div class="col-md-4 col-sm-4 col-xs-12">
                    <div class="control-group">
                        <?= $form->field($model, 'street')->textInput(['style' => 'margin: 0 auto;', 'placeholder' => $model->getAttributeLabel('street')])->label(''); ?>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12 col-sm-12 col-xs-12">
                    <div class="control-group">
                        <?= $form->field($model, 'event')->textarea([
                            'style' => 'margin: 0 auto; padding: 13px;',
                            'placeholder' => 'Причина обращения',
                            'rows' => '8'
                        ])->label(''); ?>
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="col-md-12 col-sm-12 col-xs-12">
                    <div class="control-group">
                        <?= $form->field($model, 'acordul_tc')
                            ->checkbox([
                                'label' => '<a target="_blank" href="/uploads/personal_agree.pdf">Подтверждаю свое согласие на обработку персональных данных</a>',
                                'checked' => false,
                            ]);
                        ?>
                    </div>
                </div>
            </div>

            <div class = 'button-search'>
                <div class="control-group">
                    <div class="controls">
                        <button style="width: 25%" type="submit" class="btn">Отправить</button>
                    </div>
                </div>
            </div>
        <?php ActiveForm::end() ?>
    </section>
</div>


<?php

$this->registerJs("
    $('#search-form').on('ajaxComplete', function (e, attribute, message) {
    console.log(attribute.responseJSON);
       if(attribute.responseJSON.success == false) {
            $('.warranty_hidden').show();
            $('.warranty_data').hide();
        } else if (attribute.responseJSON == false) {
            $('.warranty_data').hide();
        } else {
            $('.warranty_data').show();
            $('.warranty_hidden').hide();
            if (attribute.responseJSON.date) {
//                if (attribute.responseJSON.date.month >=1) {
                    $('.warranty_data .number').html(attribute.responseJSON.date.month);
//                } else {
//                    $('.warranty_data .number').remove();
//                }
                $('.warranty_data .number2').html(attribute.responseJSON.date.day);
            }
        }  
    });
    
    
    // update city list    
    $('#service-region_id').on('change', function () {
        $.ajax({
        url: '/load-city-by-region',
        dataType: 'html',
        type: 'get',
        data: {id: $(this).val()},
        success: function (data) {
            $('#service-city_id').empty();
            $('#service-city_id').html(data);
            $('#service-city_id').selectpicker('refresh');
        }
      });
    })  
    "
);

garanty.acv.ru/views/site/contact.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\ContactForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\captcha\Captcha;

$this->title = 'Contact';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-contact">
    <h1><?= Html::encode($this->title) ?></h1>

    <?php if (Yii::$app->session->hasFlash('contactFormSubmitted')): ?>

        <div class="alert alert-success">
            Thank you for contacting us. We will respond to you as soon as possible.
        </div>

        <p>
            Note that if you turn on the Yii debugger, you should be able
            to view the mail message on the mail panel of the debugger.
            <?php if (Yii::$app->mailer->useFileTransport): ?>
                Because the application is in development mode, the email is not sent but saved as
                a file under <code><?= Yii::getAlias(Yii::$app->mailer->fileTransportPath) ?></code>.
                Please configure the <code>useFileTransport</code> property of the <code>mail</code>
                application component to be false to enable email sending.
            <?php endif; ?>
        </p>

    <?php else: ?>

        <p>
            If you have business inquiries or other questions, please fill out the following form to contact us.
            Thank you.
        </p>

        <div class="row">
            <div class="col-lg-5">

                <?php $form = ActiveForm::begin(['id' => 'contact-form']); ?>

                    <?= $form->field($model, 'name')->textInput(['autofocus' => true]) ?>

                    <?= $form->field($model, 'email') ?>

                    <?= $form->field($model, 'subject') ?>

                    <?= $form->field($model, 'body')->textarea(['rows' => 6]) ?>

                    <?= $form->field($model, 'verifyCode')->widget(Captcha::className(), [
                        'template' => '<div class="row"><div class="col-lg-3">{image}</div><div class="col-lg-6">{input}</div></div>',
                    ]) ?>

                    <div class="form-group">
                        <?= Html::submitButton('Submit', ['class' => 'btn btn-primary', 'name' => 'contact-button']) ?>
                    </div>

                <?php ActiveForm::end(); ?>

            </div>
        </div>

    <?php endif; ?>
</div>

garanty.acv.ru/views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = 'Страница не найдена';
?>
<div class="site-error">

<!--    <h1>--><?//= Html::encode($this->title) ?><!--</h1>-->

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        Пожалуйста, попробуйте <a href="<?= \yii\helpers\Url::to('/') ?>">позже</a>.
    </p>
</div>

garanty.acv.ru/views/site/index.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Url;
use yii\widgets\ActiveForm;
use yii\helpers\Html;

$this->title = 'Проверка гарантии';
?>


<h1>Проверка гарантии:</h1>
<section class = 'form-search'>
        <?php
        $form = ActiveForm::begin([
            'id' => 'search-form',
            'action' => 'search',
            'options' => [
                'class' => 'form-horizontal',
                'enctype' => 'multipart/form-data'
            ],
        ]);
        ?>

        <div class="control-group">
            <?= $form->field($model, 'brand')->dropDownList($brand, ['class' => 'selectpicker']); ?>
        </div>

        <div class="control-group">
           <?= $form->field($model, 'serial')->textInput(['style' => 'margin: 0 auto;']); ?>
        </div>

        <div class="control-group">
            <?= $form->field($model, 'name')->dropDownList($items, ['class' => 'selectpicker', 'data-live-search' => 'true']); ?>
        </div>
        <div class = 'button-search'>
            <div class="control-group">
                <div class="controls">
                    <button type="submit" class="btn">Найти</button>
                </div>
            </div>
        </div>
    <?php ActiveForm::end() ?>
</section>
<section class="links-orders col-md-5 col-sm-6 col-xs-12">
    <div class="link-orders-block">
        <a href="<?= Url::to('/make-service') ?>">Провести сервисное обслуживание <br> оборудования</a>
    </div>
    <div class="link-orders-block">
        <a href="<?= Url::to('/call-service') ?>">Вызов специалиста при поломке <br> оборудования</a>
    </div>
    <div class="link-orders-block">
        <a href="<?= Url::to('/registry-list') ?>">Произвести регистрацию пуска <br> котла</a>
    </div>
</section>

<?php
$script = <<< JS
    $('#search-brand').on('change', function () {
        $.ajax({
            url: '/change-brand-list',
            dataType: 'html',
            type: 'get',
            data: {id: $(this).val()},
            success: function (data) {
            $('#search-name').empty();
            $('#search-name').html(data);
            $('#search-name').selectpicker('refresh');
            }
        });
    }) 
JS;
echo $this->registerJs($script, yii\web\View::POS_LOAD);
?>

garanty.acv.ru/views/site/login.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\LoginForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Login';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-login">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Please fill out the following fields to login:</p>

    <?php $form = ActiveForm::begin([
        'id' => 'login-form',
        'layout' => 'horizontal',
        'fieldConfig' => [
            'template' => "{label}\n<div class=\"col-lg-3\">{input}</div>\n<div class=\"col-lg-8\">{error}</div>",
            'labelOptions' => ['class' => 'col-lg-1 control-label'],
        ],
    ]); ?>

        <?= $form->field($model, 'username')->textInput(['autofocus' => true]) ?>

        <?= $form->field($model, 'password')->passwordInput() ?>

        <?= $form->field($model, 'rememberMe')->checkbox([
            'template' => "<div class=\"col-lg-offset-1 col-lg-3\">{input} {label}</div>\n<div class=\"col-lg-8\">{error}</div>",
        ]) ?>

        <div class="form-group">
            <div class="col-lg-offset-1 col-lg-11">
                <?= Html::submitButton('Login', ['class' => 'btn btn-primary', 'name' => 'login-button']) ?>
            </div>
        </div>

    <?php ActiveForm::end(); ?>

    <div class="col-lg-offset-1" style="color:#999;">
        You may login with <strong>admin/admin</strong> or <strong>demo/demo</strong>.<br>
        To modify the username/password, please check out the code <code>app\models\User::$users</code>.
    </div>
</div>

garanty.acv.ru/views/site/search.php
<?php
use yii\bootstrap\ActiveForm;
use yii\bootstrap\Modal;
use yii\helpers\Html;

$this->title = 'Проверка гарантии';
?>

<h1>Проверка гарантии:</h1>
<section class = 'info-box'>
    <?php if ($checkFalse): ?>
        <h2>Гарантия приостановлена  в связи с отсутствием Технического обслуживания</h2>
    <?php else: ?>
        <h2><?= ($data) ? $data->importWarranty->name : 'Ничего не найдено'; ?></h2>
        <?php if ($date): ?>
            <?php if ($date['month'] < 1 && $date['day'] < 1): ?>
                <div class = 'term'>
                    <h4 style="color: #787878;">Гарантийный срок истек <br><br> <?= date('d.m.Y', $data->end_warranty) ?></h4>
                </div>
            <?php else: ?>
                <?php if ($date['month'] >= 1): ?>
                    <div class = 'term'>
                        <p class = 'number'>  <?php echo $date['month']; ?></p><span class = 'string'>месяцев</span>
                    </div>
                <?php endif; ?>
                <div class = 'term'>
                    <p class = 'number2'>  <?php echo $date['day']; ?></p><span class = 'string'>дней</span>
                </div>
            <?php endif; ?>
        <?php endif; ?>
    <?php endif; ?>

    <a href="<?= \yii\helpers\Url::to(Yii::$app->homeUrl); ?>"> <img src="images/term-img.png" alt = 'term-img'> Назад в поиск</a>
</section>

<?php Modal::begin([
    'header' => 'Обратная связь',
]);

$form = ActiveForm::begin([
    'id' => 'contact-form',
    'action' => 'callback',
    'options' => [
        'enctype' => 'multipart/form-data'
    ],
]);
?>
<p class="title"></p>
<?= $form->field($callback, 'name')->textInput(['autofocus' => true]) ?>

<?= $form->field($callback, 'email') ?>

<?= $form->field($callback, 'body')->textarea(); ?>

<div class="">
    <?= Html::fileInput('file');  ?>
</div>
<br>
<div class="">
    <?= Html::submitButton('Отправить', ['class' => 'btn btn-primary']);  ?>
</div>

<?php ActiveForm::end() ?>
<?php Modal::end(); ?>

<?php
$script = <<< JS
    $('.rules').on('click', function() {
        $('.modal').modal('show');
        return false;
    })
JS;
echo $this->registerJs($script, yii\web\View::POS_LOAD);
?>